version: '2'
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    depends_on:
      - zookeeper
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  webserver:
    build: './webserver'
    image: web_server
    container_name: web_server
    ports: 
      - "9090:9090"
    depends_on:
      - server
    networks:
      - application
  consumer:
    build: './consumer'
    image: frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - webserver
    networks:
      - application

networks:
  application:
    driver: bridge